[package]
name = "bit_star"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
priority-queue = "1.2.3"
#priq = "0.2.0"
minimal-lexical = "0.2.1"
